### ISSUE TITLE
Initial view not removed from DOM 

### ISSUE THREAD

**Issue by ebenpack** [Tehnix/miso-isomorphic-stack#6]
The initial SSR view isn't being removed from the DOM when the client-side SPA loads. This causes two copies of the initial view to be stacked on the page initially, and the initial view continues to persist on the page even as the SPA view changes. The initial view is not interactive (e.g. clicking the 'Go to /flipped' has no effect on either copy of the view).

Initial view:
<img width="167" alt="screen shot 2018-08-30 at 10 50 11 am" src="https://user-images.githubusercontent.com/3874640/44860041-6578c500-ac43-11e8-8888-fab92579c683.png">

After interacting with the app:
<img width="110" alt="screen shot 2018-08-30 at 11 20 03 am" src="https://user-images.githubusercontent.com/3874640/44861522-acb48500-ac46-11e8-8f9a-eb8a97a41404.png">

This seems to be related to the addition of JSaddle. Reverting the JSaddle specific changes in frontend/Main.hs from the latest commit seem to resolve the issue. I'm not sure exactly what the intention is for using JSaddle here, but it seems like it fixes an issue I had previously where it wasn't really possible to specify a `mountPoint` for the app, so hopefully there's a better solution than just reverting.

I'm going to poke at this a bit, and see if I can't submit a PR, but tbh the solution is not immediately apparent to me.

**Comment by ebenpack** [comment]
Ah, okay the issue seems to be related more specifically to the use of `miso` vs. `startApp`. It looks like `miso` doesn't perform an initial diff, but it also doen't seem to play well with `mountPoint`, whereas `startApp` performs an initial diff (which seems to be bugged), but works better with `mountPoint`.

This seems to be an upstream issue, so I'm going to look into that. For the time being, it seems like something like the following could be done (although it's admittedly a bit ugly):

    main :: IO ()
    main =
      JSaddle.run 8080 $ do
        currentURI <- Miso.getCurrentURI
        Miso.miso (\_ -> App { initialAction = Common.NoOp
                          , model = Common.initialModel currentURI
                          , update = Miso.fromTransition . Frontend.updateModel
                          , view = Common.viewModel
                          , events = Miso.defaultEvents
                          , subs = [Miso.uriSub Common.HandleURI]
                          , mountPoint = Nothing
                          })

**Comment by Tehnix** [comment]
Don't know how I missed this, but good catch!

I was attempting to switch to the new JSAddle support, but am not quite sure where the flags need to go in all this (the documentation on usage is a bit sparse atm).

I'll try to look into it.

**Comment by Tehnix** [comment]
Ah, I see you've made a fairly thorough issue on it already at https://github.com/dmjio/miso/issues/455. 

All the examples I've found use the combination of JSAddle.run and `startApp` with `mountPoint` set to `Nothing` ([examples/mario](https://github.com/dmjio/miso/blob/5c3d01780bce2f803bf10d531c876250be5eebc6/examples/mario/Main.hs#L20), [miso/main](https://github.com/dmjio/miso/blob/5c3d01780bce2f803bf10d531c876250be5eebc6/exe/Main.hs#L28), [examples/route](https://github.com/dmjio/miso/blob/5c3d01780bce2f803bf10d531c876250be5eebc6/examples/router/Main.hs#L38)), so I assume it should be able to work this way. I guess, as you mention in your issue, it's the isomorphic aspect of it that breaks down.

I'm using your workaround for now, and will update it to the correct solution once it's fixed.

**Comment by ebenpack** [comment]
So, digging more into miso, I think this is down to what `miso`  and `startApp` are intended for, and the move in the last commit from using `miso` to using `startApp`. Specifically:

    -- | Runs an isomorphic miso application
    -- Assumes the pre-rendered DOM is already present
    miso :: Eq model => (URI -> App model action) -> JSM ()

So I kind of threw out a red-herring with JSaddle. I think either the solution above, or something like the following (assuming it works) is probably just the right thing to be doing for isomorphic:

    main :: IO ()
    main =
      JSaddle.run 8080 $ do
        Miso.miso (\currentURI -> App { initialAction = Common.NoOp

The issue you mention above I think is kind of a separate thing, which I don't think affects this project, or this specific issue. It's a slight functional change I personally have a use for, but since this project doesn't try to use a mount point it shouldn't have any effect either way.

Anyway, great work on this project! I think I'm going to close this issue out, as it looks like you've remedied the issue.
